services:
  nginx:
    image: nginx:latest
    volumes:
      - ./:/var/www/html
      - ./docker/nginx/conf.d:/etc/nginx/conf.d
    ports:
      - 8891:80
    depends_on:
      - app
    container_name: project_framework_mvc_nginx

  app:
    build:
      context: .
      dockerfile: ./docker/app/Dockerfile
    volumes:
      - ./:/var/www/html
    depends_on:
      - db
    container_name: project_framework_mvc_app

  db:
    image: mysql:8.0
    restart: always
    ports:
      - 8092:3306
    environment:
      MYSQL_DATABASE: framework_mvc_db
      MYSQL_ROOT_PASSWORD: root
    container_name: project_framework_mvc_db
